labels:
    beer_cols:
        - Name
        - Type
        - ABV
        - Pour
        - Cost

    food_cols:
        - Food
        - Sang Witches

    merch_cols:
        - Item
        - Cost

times:
    beer_menu_1:
        - 30
    beer_menu_2:
        - 5
    food_menu:
        - 20
    merch_menu:
        - 10
        