labels:
    beer_cols:
        - Name
        - Type
        - ABV
        - Pour
        - Cost

    food_cols:
        - Food
        - Halfway Cooks
        - Sang Witches

    merch_cols:
        - Item
        - Cost
