labels:
    beer_cols:
        - Name
        - Type
        - ABV
        - Pour
        - Cost

    food_cols:
        - Twin Beaks ^^
        - Halfway Cooks
        - Cheese

    merch_cols:
        - Item
        - Cost
