labels:
    beer_cols:
        - Name
        - Type
        - ABV
        - Pour
        - Cost

    food_cols:
        - Heaps
        - Halfway Cooks
        - Sandwhiches

    merch_cols:
        - Item
        - Cost
