labels:
    beer_cols:
        - Name
        - Type
        - ABV
        - Pour
        - Cost

    food_cols:
        - Twin Beaks Wings ^^
        - Halfway Cooks Fries!
        - Cheese

    merch_cols:
        - Item
        - Cost
